In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import os

# Get the path to the project directory
project_path = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(os.path.join(project_path, "src"))

from load_data import load_data
from preprocessing import Preprocessing
from train import TrainModel
from evaluate import Evaluation
from utils import load_model
from inference import InferenceModel

/home/nathalie/Desktop/projects/loan-prediction/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv('../data/loan_data_predict.csv')

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban

In [4]:
data_prep = Preprocessing(inference_data=df)

In [5]:
data_prep.preprocess_for_inference()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,0,0,0.081691,-0.516483,-0.007253,8,1,2
1,1,1,1,0,0,-0.151994,-0.064532,-0.260675,8,1,0
2,1,1,0,0,1,-0.444191,-0.516483,-1.018908,8,1,2
3,1,1,0,1,0,-0.521163,0.190214,-0.358511,8,1,2
4,1,0,0,0,0,0.109563,-0.516483,-0.101691,8,1,2
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,-0.462650,-0.516483,-0.957760,8,1,0
610,1,1,3,0,0,-0.240041,-0.516483,-1.336876,5,1,0
611,1,1,1,0,0,0.492023,-0.444554,1.268020,8,1,2
612,1,1,2,0,0,0.401761,-0.516483,0.460869,8,1,2
613,0,0,0,0,1,-0.151994,-0.516483,-0.199527,8,0,1

In [6]:
df = data_prep.inference_data

In [7]:
predictions = InferenceModel('../models/model.pkl')

In [8]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,0,0,0.081691,-0.516483,-0.007253,8,1,2
1,1,1,1,0,0,-0.151994,-0.064532,-0.260675,8,1,0
2,1,1,0,0,1,-0.444191,-0.516483,-1.018908,8,1,2
3,1,1,0,1,0,-0.521163,0.190214,-0.358511,8,1,2
4,1,0,0,0,0,0.109563,-0.516483,-0.101691,8,1,2
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,-0.462650,-0.516483,-0.957760,8,1,0
610,1,1,3,0,0,-0.240041,-0.516483,-1.336876,5,1,0
611,1,1,1,0,0,0.492023,-0.444554,1.268020,8,1,2
612,1,1,2,0,0,0.401761,-0.516483,0.460869,8,1,2
613,0,0,0,0,1,-0.151994,-0.516483,-0.199527,8,0,1

In [9]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,0,0,0.081691,-0.516483,-0.007253,8,1,2
1,1,1,1,0,0,-0.151994,-0.064532,-0.260675,8,1,0
2,1,1,0,0,1,-0.444191,-0.516483,-1.018908,8,1,2
3,1,1,0,1,0,-0.521163,0.190214,-0.358511,8,1,2
4,1,0,0,0,0,0.109563,-0.516483,-0.101691,8,1,2
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,-0.462650,-0.516483,-0.957760,8,1,0
610,1,1,3,0,0,-0.240041,-0.516483,-1.336876,5,1,0
611,1,1,1,0,0,0.492023,-0.444554,1.268020,8,1,2
612,1,1,2,0,0,0.401761,-0.516483,0.460869,8,1,2
613,0,0,0,0,1,-0.151994,-0.516483,-0.199527,8,0,1

In [10]:
preds = predictions.predict(df)

In [11]:
preds

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,predictions
0,1,0,0,0,0,0.081691,-0.516483,-0.007253,8,1,2,1
1,1,1,1,0,0,-0.151994,-0.064532,-0.260675,8,1,0,0
2,1,1,0,0,1,-0.444191,-0.516483,-1.018908,8,1,2,1
3,1,1,0,1,0,-0.521163,0.190214,-0.358511,8,1,2,1
4,1,0,0,0,0,0.109563,-0.516483,-0.101691,8,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,-0.462650,-0.516483,-0.957760,8,1,0,0
610,1,1,3,0,0,-0.240041,-0.516483,-1.336876,5,1,0,1
611,1,1,1,0,0,0.492023,-0.444554,1.268020,8,1,2,1
612,1,1,2,0,0,0.401761,-0.516483,0.460869,8,1,2,1
613,0,0,0,0,1,-0.151994,-0.516483,-0.199527,8,0,1,0